name: realtime_battery_indicator
description: A realtime good looking customizable battery indicator for all platforms.
version: 1.0.2
homepage: https://github.com/mantreshkhurana/realtime_battery_indicator
repository: https://github.com/mantreshkhurana/realtime_battery_indicator

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  battery_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
